### ISSUE TITLE
Mount external SD card at /mnt/sdcard

### ISSUE THREAD

**Issue by joneschrisg** [mozilla-b2g/android-device-m4#1]
The m4 has a directory in its /data partition mounted through FUSE at /mnt/sdcard (why, I dunno!), IIRC.  This is slightly crazy, but more importantly prevents us from using USB mass storage with /sdcard.  Since external SD card mounted at /sdcard is the more important configuration, we need to find a way to fix this ASAP.  Otherwise users won't be able to upload/download media from the device, which will be a major dogfooding problem.

One possibility is to implement MTP, but that's probably a fair amount of work, and not the code we'll eventually ship.

The second option, which @michaelwu and I discussed today, is hacking the app_process script to mount the external card at /sdcard and ignore/undo the FUSE hackery.  This is simpler and keeps the Optimus L5 hackery limited to the Optimius L5.

CC @andreasgal I don't have an L5 or I'd grab this, but IMHO this should block distributing phones for dogfooding.  We won't be able to ship FOTA updates for these guys.

**Comment by michaelwu** [comment]
@dhylands , what do you think?

MTP isn't code we'd ship, but we wouldn't throw it away either so it wouldn't be entirely wasted work. I would not block phone distribution on this because the phones do not come with sdcards. A compromise could be to disable the hack when a sdcard is inserted.

**Comment by joneschrisg** [comment]
Another problem is that USB mass storage is 100% supported on all OSes, but MTP support is rather spotty in comparison.

We need to prefer using UMS.

**Comment by dhylands** [comment]
Personally, I think that MTP, or some type of web/network sharing is the way to go in the long run. The only advantage that UMS has is the universality of client support.

**Comment by marcofreda527** [comment]
Dear Chris,

I tried to install a SD Card into m4 and enabled the UMS from setting.
I can a see a removable storage appeared on my desktop after connecting the
USB between them.

By the way, I want to clarify some thing.
1. The FUSE system is not mounted a folder from /data. It should mount a
   dedicated partition from internal eMMC.
2. In recent phone with internal eMMC, the normal deployment of SD Card is
     a. Mount a dedicated partition from internal eMMC to /mnt/sdcard. So
   user can perform many AP which need /mnt/sdcard without external SD Card.
     b. Mount external SD Card to /mnt/sdcard/usbstorage. So the file
   system exported via UMS to Host will contained the internal eMMC partition
   and external SD Card.

So what we need to is to design a configuration file for eMMC or Nand Flash
devices to mount their storage.

**Comment by joneschrisg** [comment]
@marcofreda527 it's a little hard for me to tell the difference between the things you say "should be" true, compared to things that "are true" for the L5.  I don't have an L5 so I can't check things for myself, sorry.

We should back up a bit and list the goals here.  This issue was filed with not enough information.
- B2G v1 will only support USB mass storage.  No MTP.
- Gecko is currently configured to only use the "/sdcard" folder, whatever the underlying storage medium is --- internal flash, external SD card, FUSE fs, separate partition, folder, whatever.

Since the L5 is a demo device, not a shipping target, we don't want to new code to Gecko to support it, if possible.  That's programmer time that would be better spent on issues that affect the ship target.

So the goal is to make the L5 to look and behave as much like the shipping target as possible.  Ideally, the L5 would
- have an external SD card mounted at /sdcard --> /mnt/sdcard
- have /mnt/sdcard mountable through USB mass storage
- (any other storage partitions would be ignored)

If we're forced to use internal storage instead of an external SD card, for some reason, that would be OK but not ideal.  It would be different from the shipping target, and that's bad.

Does this make sense?

**Comment by marcofreda527** [comment]
Hi Chris,

Yes, if we want to focus on the features for shipping target.
Then we need to ignore other variations on deployment of sd card.

But I want to remind that the HW spec of shipping target should use NAND
flash as internal storage not eMMC.
Or we will meet the issue on L5.
